resilience4j:
  circuitbreaker:
    instances:
      sim-customerService:
        failure-rate-threshold: 50
        ring-buffer-size-in-closed-state: 2
        ring-buffer-size-in-half-open-state: 2
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true